// Hata yönetimi try catch kullanımı

let items;
try {
    items.forEach(item => {console.log(item)})

} catch (error) {

    console.log("Hata Yönetimi Çalışıo")

    let info = "kodluyoruz"
    console.log(info)
} 



